/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import edu.memphis.ccrg.lida.framework.ModuleName;
import edu.memphis.ccrg.lida.framework.gui.panels.GuiPanel;
import edu.memphis.ccrg.lida.framework.gui.panels.GuiPanelImpl;
import java.util.logging.Level;
import java.util.logging.Logger;
import modules.Environment;

/**
 *
 * @author lucas
 */
public class ActionPanel extends GuiPanelImpl {
    
    private static final Logger logger = Logger.getLogger(ActionPanel.class.getCanonicalName());
    private Environment environment;

    /**
     * Creates new form ActionPanel
     */
    public ActionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        actionLabel = new javax.swing.JLabel();
        rotateButton = new javax.swing.JToggleButton();
        forwardButton = new javax.swing.JToggleButton();
        getJewelButton = new javax.swing.JToggleButton();
        goToJewelButton = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Chosen Action:");

        actionLabel.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        actionLabel.setText("Forward");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(actionLabel)
                        .addGap(49, 49, 49))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(actionLabel)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        rotateButton.setText("Rotate");

        forwardButton.setText("Forward");

        getJewelButton.setText("Get jewel");

        goToJewelButton.setText("Go to jewel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forwardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rotateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goToJewelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(getJewelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(forwardButton)
                        .addGap(18, 18, 18)
                        .addComponent(rotateButton)
                        .addGap(18, 18, 18)
                        .addComponent(goToJewelButton)
                        .addGap(18, 18, 18)
                        .addComponent(getJewelButton)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void initPanel(String[] param) {
        environment = (Environment) agent.getSubmodule(ModuleName.Environment);
        if (environment != null) {
            refresh();
        } else {
            logger.log(Level.WARNING,
                    "Unable to parse module {1} Panel not initialized.",
                    new Object[]{0L, param[0]});
        }
    }
    
        @Override
    public void refresh() {
        int lastPressedButton = environment.getLastPressedButton();
        switch(lastPressedButton){
            case 1:
                forwardButton.setSelected(true);
                rotateButton.setSelected(false);
                goToJewelButton.setSelected(false);
                getJewelButton.setSelected(false);
                actionLabel.setText("Forward");
                break;
            case 2:
                forwardButton.setSelected(false);
                rotateButton.setSelected(true);
                goToJewelButton.setSelected(false);
                getJewelButton.setSelected(false);
                actionLabel.setText("Rotate");
                break;
            case 3:
                forwardButton.setSelected(false);
                rotateButton.setSelected(false);
                goToJewelButton.setSelected(true);
                getJewelButton.setSelected(false);
                actionLabel.setText("Go to Jewel");
                break;
            case 4:
                forwardButton.setSelected(false);
                rotateButton.setSelected(false);
                goToJewelButton.setSelected(false);
                getJewelButton.setSelected(true);
                actionLabel.setText("Get Jewel");
                break;
            default:
                forwardButton.setSelected(false);
                rotateButton.setSelected(false);
                goToJewelButton.setSelected(false);
                getJewelButton.setSelected(false);
                actionLabel.setText("None");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JToggleButton forwardButton;
    private javax.swing.JToggleButton getJewelButton;
    private javax.swing.JToggleButton goToJewelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    private javax.swing.JToggleButton rotateButton;
    // End of variables declaration//GEN-END:variables
}
