/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import util.Constants;
import ws3dproxy.CommandExecException;
import ws3dproxy.WS3DProxy;
import ws3dproxy.model.Bag;
import ws3dproxy.model.Creature;
import ws3dproxy.model.CreatureState;
import ws3dproxy.model.Leaflet;
import ws3dproxy.model.Thing;
import ws3dproxy.model.World;
import ws3dproxy.model.WorldPoint;


/**
 *
 * @author lucas
 */
public class CreatureFrame extends javax.swing.JFrame{
    
    WS3DProxy proxy = null;
    World world = null;
    Map<String,String> creaturesCreated = new HashMap<String,String>();
    Creature selectedCreature= null;
    Bag selectedCreaturesBag = null;
    WorldPoint selectedCreatureInitialPoint = null;
    WorldPoint selectedCreatureFinalPoint = null;
    double selectedCreatureInitialPitch = 0 ;
    double selectedCreatureFinalPitch = 0 ;
    
    /**
     * Creates new form CreatureFrame
     */
    public CreatureFrame(WS3DProxy proxy, World world) {
        this.proxy = proxy;
        this.world = world;
        initComponents();
        addCreaturesToComboBox(selectCreatureComboBox);
    }
    
    private void addCreaturesToComboBox( JComboBox<String> comboBox ){
        List<Thing> things;
	try {
            things = World.getWorldEntities();
            things.forEach(thing -> {
                if(thing.getName().contains("Creature")) {
                    creaturesCreated.put(Integer.toString(things.indexOf(thing)), thing.getName());
                }
            });
	} catch (CommandExecException ex) {
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
	}
    	
        comboBox.removeAllItems();
        creaturesCreated.entrySet().forEach((pair) -> comboBox.addItem(pair.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        newCreaturePanel = new javax.swing.JPanel();
        creatureColorComboBox = new javax.swing.JComboBox<>();
        creatureColorLabel = new javax.swing.JLabel();
        creatureXPositionLabel = new javax.swing.JLabel();
        creatureYPositionLabel = new javax.swing.JLabel();
        creatureXPositionTextField = new javax.swing.JTextField();
        creatureYPositionTextField = new javax.swing.JTextField();
        createCreatureButton = new javax.swing.JButton();
        pitchSlider = new javax.swing.JSlider();
        pitchLabel = new javax.swing.JLabel();
        zeroLabel = new javax.swing.JLabel();
        thsLabel = new javax.swing.JLabel();
        updateCreaturePanel = new javax.swing.JPanel();
        updateCreatureLabel = new javax.swing.JLabel();
        selectCreatureComboBox = new javax.swing.JComboBox<>();
        moveCreaturePanel = new javax.swing.JPanel();
        moveUpButton = new javax.swing.JButton();
        clockwiseRotationButton = new javax.swing.JButton();
        moveDownButton = new javax.swing.JButton();
        antiClockwiseRotationButton = new javax.swing.JButton();
        fuelPane = new javax.swing.JPanel();
        fuelProgressBar = new javax.swing.JProgressBar();
        actionPanel = new javax.swing.JPanel();
        eatButton = new javax.swing.JButton();
        putInBagButton = new javax.swing.JButton();
        bagPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bagTable = new javax.swing.JTable();
        socrePanel = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        scoreTextField = new javax.swing.JTextField();
        leafletPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leafletTable = new javax.swing.JTable();
        leafletButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creature");
        setAlwaysOnTop(true);

        newCreaturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Creature", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        creatureColorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yellow", "Red" }));

        creatureColorLabel.setText("Color");

        creatureXPositionLabel.setText("X position ");

        creatureYPositionLabel.setText("Y position");

        creatureXPositionTextField.setText("0");

        creatureYPositionTextField.setText("0");

        createCreatureButton.setText("Create Creature");
        createCreatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCreatureButtonActionPerformed(evt);
            }
        });

        pitchSlider.setMaximum(360);
        pitchSlider.setValue(0);

        pitchLabel.setText("Pitch");

        zeroLabel.setText("0º");

        thsLabel.setText("360º");

        javax.swing.GroupLayout newCreaturePanelLayout = new javax.swing.GroupLayout(newCreaturePanel);
        newCreaturePanel.setLayout(newCreaturePanelLayout);
        newCreaturePanelLayout.setHorizontalGroup(
            newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCreaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newCreaturePanelLayout.createSequentialGroup()
                        .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creatureXPositionLabel)
                            .addComponent(creatureYPositionLabel)
                            .addComponent(creatureColorLabel))
                        .addGap(4, 4, 4)
                        .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(creatureXPositionTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creatureColorComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 112, Short.MAX_VALUE)
                            .addComponent(creatureYPositionTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(newCreaturePanelLayout.createSequentialGroup()
                        .addComponent(pitchLabel)
                        .addGap(38, 38, 38)
                        .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newCreaturePanelLayout.createSequentialGroup()
                                .addComponent(zeroLabel)
                                .addGap(73, 73, 73)
                                .addComponent(thsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addComponent(pitchSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newCreaturePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createCreatureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        newCreaturePanelLayout.setVerticalGroup(
            newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCreaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newCreaturePanelLayout.createSequentialGroup()
                        .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creatureColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creatureColorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creatureXPositionLabel)
                            .addComponent(creatureXPositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creatureYPositionLabel)
                            .addComponent(creatureYPositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pitchSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pitchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zeroLabel)
                    .addComponent(thsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createCreatureButton)
                .addContainerGap())
        );

        updateCreaturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Creature", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        updateCreatureLabel.setText("Creature");

        selectCreatureComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCreatureComboBoxActionPerformed(evt);
            }
        });

        moveCreaturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Move", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        moveUpButton.setText("Move Forward");
        moveUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveUpButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moveUpButtonMouseReleased(evt);
            }
        });

        clockwiseRotationButton.setText("Rotate Right");
        clockwiseRotationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clockwiseRotationButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clockwiseRotationButtonMouseReleased(evt);
            }
        });

        moveDownButton.setText("Move Backward");
        moveDownButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveDownButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moveDownButtonMouseReleased(evt);
            }
        });

        antiClockwiseRotationButton.setText("Rotate Left");
        antiClockwiseRotationButton.setToolTipText("");
        antiClockwiseRotationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                antiClockwiseRotationButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                antiClockwiseRotationButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout moveCreaturePanelLayout = new javax.swing.GroupLayout(moveCreaturePanel);
        moveCreaturePanel.setLayout(moveCreaturePanelLayout);
        moveCreaturePanelLayout.setHorizontalGroup(
            moveCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moveCreaturePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(antiClockwiseRotationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moveCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moveUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moveDownButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockwiseRotationButton)
                .addGap(38, 38, 38))
        );
        moveCreaturePanelLayout.setVerticalGroup(
            moveCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moveCreaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveUpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(moveCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(antiClockwiseRotationButton)
                    .addComponent(moveDownButton)
                    .addComponent(clockwiseRotationButton))
                .addContainerGap())
        );

        fuelPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fuel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        fuelProgressBar.setForeground(new java.awt.Color(233, 84, 32));
        fuelProgressBar.setMaximum(1000);
        fuelProgressBar.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout fuelPaneLayout = new javax.swing.GroupLayout(fuelPane);
        fuelPane.setLayout(fuelPaneLayout);
        fuelPaneLayout.setHorizontalGroup(
            fuelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fuelPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fuelProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fuelPaneLayout.setVerticalGroup(
            fuelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fuelPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(fuelProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updateCreaturePanelLayout = new javax.swing.GroupLayout(updateCreaturePanel);
        updateCreaturePanel.setLayout(updateCreaturePanelLayout);
        updateCreaturePanelLayout.setHorizontalGroup(
            updateCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCreaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveCreaturePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(updateCreaturePanelLayout.createSequentialGroup()
                        .addComponent(updateCreatureLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectCreatureComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(fuelPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        updateCreaturePanelLayout.setVerticalGroup(
            updateCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCreaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCreatureLabel)
                    .addComponent(selectCreatureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveCreaturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuelPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        actionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        eatButton.setText("Eat!");
        eatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eatButtonActionPerformed(evt);
            }
        });

        putInBagButton.setText("Bag!");
        putInBagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putInBagButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(putInBagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eatButton)
                    .addComponent(putInBagButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bagPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bag", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bagTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NP Food", null},
                {"P Food", null},
                {"Magenta", null},
                {"Blue", null},
                {"Red", null},
                {"Green", null},
                {"White", null},
                {"Yellow", null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bagTable.setFocusable(false);
        bagTable.setOpaque(false);
        bagTable.setRequestFocusEnabled(false);
        bagTable.getTableHeader().setResizingAllowed(false);
        bagTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(bagTable);
        if (bagTable.getColumnModel().getColumnCount() > 0) {
            bagTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout bagPanelLayout = new javax.swing.GroupLayout(bagPanel);
        bagPanel.setLayout(bagPanelLayout);
        bagPanelLayout.setHorizontalGroup(
            bagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bagPanelLayout.setVerticalGroup(
            bagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bagPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        socrePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Score", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        scoreLabel.setText("Score");

        scoreTextField.setFocusable(false);

        javax.swing.GroupLayout socrePanelLayout = new javax.swing.GroupLayout(socrePanel);
        socrePanel.setLayout(socrePanelLayout);
        socrePanelLayout.setHorizontalGroup(
            socrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreTextField)
                .addContainerGap())
        );
        socrePanelLayout.setVerticalGroup(
            socrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socrePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(socrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel)
                    .addComponent(scoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        leafletPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Leaflet", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        leafletTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Red", null, null, null},
                {"Green", null, null, null},
                {"Blue", null, null, null},
                {"Magenta", null, null, null},
                {"White", null, null, null},
                {"Yellow", null, null, null},
                {"Score", null, null, null},
                {"Status", null, null, null}
            },
            new String [] {
                "Object", "Leaflet1", "Leaflet2", "Leaflet3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        leafletTable.setColumnSelectionAllowed(true);
        leafletTable.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(leafletTable);
        if (leafletTable.getColumnModel().getColumnCount() > 0) {
            leafletTable.getColumnModel().getColumn(0).setResizable(false);
            leafletTable.getColumnModel().getColumn(1).setResizable(false);
            leafletTable.getColumnModel().getColumn(2).setResizable(false);
            leafletTable.getColumnModel().getColumn(3).setResizable(false);
        }

        leafletButton.setText("Deliver Leaflet");
        leafletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leafletButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leafletPanelLayout = new javax.swing.GroupLayout(leafletPanel);
        leafletPanel.setLayout(leafletPanelLayout);
        leafletPanelLayout.setHorizontalGroup(
            leafletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leafletPanelLayout.createSequentialGroup()
                .addGroup(leafletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leafletPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(leafletPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(leafletButton, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leafletPanelLayout.setVerticalGroup(
            leafletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leafletPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leafletButton)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(actionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newCreaturePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(socrePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(leafletPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(updateCreaturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newCreaturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateCreaturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(socrePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leafletPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCreatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCreatureButtonActionPerformed
        try {
            int xPosition = Integer.parseInt(creatureXPositionTextField.getText());
            int yPosition = Integer.parseInt(creatureYPositionTextField.getText());
            int color = creatureColorComboBox.getSelectedIndex();
            int pitch = pitchSlider.getValue();
            Creature creature = this.proxy.createCreature(xPosition, yPosition, pitch, color);
            creature.updateBag();
            creature.updateState();
            //creature.genLeaflet();
            creature.getLeaflets().forEach(l -> {
                System.out.println(l.toString());
                
            });
            
            creaturesCreated.put(creature.getIndex(), creature.getName());
            selectCreatureComboBox.addItem(creature.getName());
            JOptionPane.showMessageDialog(this, "Creature created with name: "+creature.getName());    
        } catch (CommandExecException ex) {
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to create a creature!");
        }
    }//GEN-LAST:event_createCreatureButtonActionPerformed

    private void antiClockwiseRotationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antiClockwiseRotationButtonMouseReleased
        stopSelectedCreature();
    }//GEN-LAST:event_antiClockwiseRotationButtonMouseReleased

    private void antiClockwiseRotationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antiClockwiseRotationButtonMousePressed
        try {
            this.selectedCreature.rotate(-Constants.CREATURE_VELOCITY);
            this.selectedCreature.start();
        } catch (CommandExecException ex) {
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_antiClockwiseRotationButtonMousePressed

    private void moveDownButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveDownButtonMouseReleased
        stopSelectedCreature();
    }//GEN-LAST:event_moveDownButtonMouseReleased

    private void moveDownButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveDownButtonMousePressed
        try {
            this.selectedCreature.move(-Constants.CREATURE_VELOCITY, -Constants.CREATURE_VELOCITY, 0);
            this.selectedCreature.start();
        } catch (CommandExecException ex) {
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_moveDownButtonMousePressed

    private void clockwiseRotationButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockwiseRotationButtonMouseReleased
        stopSelectedCreature();
    }//GEN-LAST:event_clockwiseRotationButtonMouseReleased

    private void clockwiseRotationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockwiseRotationButtonMousePressed
        try {
            this.selectedCreature.rotate(Constants.CREATURE_VELOCITY);
            this.selectedCreature.start();
        } catch (CommandExecException ex) {
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clockwiseRotationButtonMousePressed

    private void moveUpButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveUpButtonMouseReleased
        stopSelectedCreature();
    }//GEN-LAST:event_moveUpButtonMouseReleased

    private void moveUpButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveUpButtonMousePressed
        try {
            this.selectedCreature.move(Constants.CREATURE_VELOCITY, Constants.CREATURE_VELOCITY, 0);
            this.selectedCreature.start();
        } catch (CommandExecException ex) {
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_moveUpButtonMousePressed

    private void selectCreatureComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCreatureComboBoxActionPerformed
        try {
            this.selectedCreature = proxy.getCreature(Integer.toString(selectCreatureComboBox.getSelectedIndex()));
            selectedCreaturesBag = selectedCreature.getBag();
            setUpBagPanel();
            setUpScorePanel();
            setUpLeafletPanel();
            this.selectedCreatureInitialPoint = new WorldPoint(selectedCreature.getAttributes().getCOM().getX(), selectedCreature.getAttributes().getCOM().getY());
            selectedCreatureInitialPitch =  selectedCreature.getAttributes().getPitch();
            int fuel = (int) selectedCreature.getFuel();
            fuelProgressBar.setValue(fuel);
        } catch (CommandExecException ex) {
            JOptionPane.showMessageDialog(this, "Falied to select creature!");
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_selectCreatureComboBoxActionPerformed

    private void eatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eatButtonActionPerformed
        Thing firstThingSeen = selectedCreature.getThingsInCameraFrustrum().get(0);
        String type = firstThingSeen.getName().split(Constants.UNDERSROCE)[Constants.ZERO];
        if(type.equalsIgnoreCase(Constants.PFOOD) || type.equalsIgnoreCase(Constants.NPFOOD)){
            if(selectedCreature.calculateDistanceTo(firstThingSeen) <= Constants.MINIMUM_DISTANCE) 
                try {
                    selectedCreature.eatIt(firstThingSeen.getName());
                    setUpScorePanel();
            } catch (CommandExecException ex) {
                Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(this,"You can't eat this");
        }
      
       
    }//GEN-LAST:event_eatButtonActionPerformed

    private void putInBagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putInBagButtonActionPerformed
        Thing firstThingSeen = selectedCreature.getThingsInCameraFrustrum().get(0);
        String type = firstThingSeen.getName().split(Constants.UNDERSROCE)[Constants.ZERO];
        if(type.equalsIgnoreCase(Constants.JEWEL)){
            if(selectedCreature.calculateDistanceTo(firstThingSeen) <= Constants.MINIMUM_DISTANCE) 
                try {
                    selectedCreature.putInSack(firstThingSeen.getName());
                    selectedCreaturesBag = selectedCreature.updateBag();
                    int totalMagentaJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_MAGENTA);
                    int totalBlueJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_BLUE);
                    int totalRedJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_RED);
                    int totalGreenJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_GREEN);
                    int totalWhiteJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_WHITE);
                    int totalYellowJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_YELLOW);
                    int totalJewel = selectedCreaturesBag.getTotalNumberCrystals();
                    int totalFood = selectedCreaturesBag.getTotalNumberFood();
                    int totalNPFood = selectedCreaturesBag.getNumberNPFood();
                    int totalPFood = selectedCreaturesBag.getNumberPFood();
                    updateCreaturesBag(totalFood, 
                        totalJewel, 
                        totalPFood, totalNPFood,
                        totalRedJewel, totalGreenJewel, 
                        totalBlueJewel, totalYellowJewel, totalMagentaJewel, totalWhiteJewel);
                    setUpBagPanel();
            } catch (CommandExecException ex) {
                Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            JOptionPane.showMessageDialog(this,"You can't keep this");
        }
    }//GEN-LAST:event_putInBagButtonActionPerformed

    private void leafletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leafletButtonActionPerformed
        int columnSelected = leafletTable.getSelectedColumn();
        if(columnSelected > 0){
            try {
                Leaflet leaflet = selectedCreature.getLeaflets().get(columnSelected-1);
               
                    String leafletId = Long.toString(leaflet.getID());
                    leaflet.setSituation(1);
                    selectedCreature.deliverLeaflet(leafletId);

            } catch (CommandExecException ex) {
                Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to deliver leaflet");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Select a valid column");
        }
       selectedCreature.updateState();
       setUpBagPanel();
       setUpLeafletPanel();
       setUpScorePanel();
    }//GEN-LAST:event_leafletButtonActionPerformed

    
    private void stopSelectedCreature(){
        try{ 
            this.selectedCreature.stop();
            this.selectedCreature.updateState();
            this.selectedCreatureFinalPoint = new WorldPoint(selectedCreature.getAttributes().getCOM().getX(), selectedCreature.getAttributes().getCOM().getY());
            this.selectedCreatureFinalPitch = selectedCreature.getAttributes().getPitch();
            
            updateCreature();
        } catch (CommandExecException ex) {
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void updateCreaturesBag(int totalFood,int totalJewels, int totalPFood, int totalNPFood,int totalRedJewel, int totalGreenJewel, int totalBlueJewel, int totalYellowJewel, int totalMagentaJewel, int totalWhiteJewel){
       List<Integer> jewelsPerType = new ArrayList<>();
       jewelsPerType.add(totalRedJewel);
       jewelsPerType.add(totalGreenJewel);
       jewelsPerType.add(totalBlueJewel);
       jewelsPerType.add(totalYellowJewel);
       jewelsPerType.add(totalMagentaJewel);
       jewelsPerType.add(totalWhiteJewel);
       selectedCreaturesBag.update(totalFood, 
               totalJewels, 
               totalPFood, 
               totalNPFood, 
               jewelsPerType);
    }
    
    private void updateCreature(){
        this.selectedCreature.updateState();
        double fuel = selectedCreature.getAttributes().getFuel();
        fuelProgressBar.setValue((int)fuel);
        selectedCreature.update(selectedCreature.getIndex(), 
                selectedCreature.getColor(), 
                selectedCreature.getSpeed(), 
                selectedCreature.getWheel(), 
                selectedCreature.getAttributes().getPitch(), 
                selectedCreature.getAttributes().getFuel(), 
                selectedCreature.getAttributes().getSerotonin(), 
                selectedCreature.getAttributes().getEndorphine(), 
                selectedCreature.getAttributes().getScore(), 
                selectedCreatureFinalPoint, 
                selectedCreature.getAttributes().getX1(), 
                selectedCreature.getAttributes().getY1(), 
                selectedCreature.getAttributes().getX2(), 
                selectedCreature.getAttributes().getY2(), 
                selectedCreature.getLeaflets(),
                0);
    }
    
    
     public void setUpBagPanel(){
        int totalNPFood = selectedCreaturesBag.getNumberNPFood();
        int totalPFood = selectedCreaturesBag.getNumberPFood();
        int totalMagentaJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_MAGENTA);
        int totalBlueJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_BLUE);
        int totalRedJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_RED);
        int totalGreenJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_GREEN);
        int totalWhiteJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_WHITE);
        int totalYellowJewel = selectedCreaturesBag.getNumberCrystalPerType(Constants.COLOR_YELLOW);
        bagTable.setValueAt(totalNPFood, 0, 1);
        bagTable.setValueAt(totalPFood, 1, 1);
        bagTable.setValueAt(totalMagentaJewel, 2, 1);
        bagTable.setValueAt(totalBlueJewel, 3, 1);
        bagTable.setValueAt(totalRedJewel, 4, 1);
        bagTable.setValueAt(totalGreenJewel, 5, 1);
        bagTable.setValueAt(totalWhiteJewel, 6, 1);
        bagTable.setValueAt(totalYellowJewel, 7, 1);
    }
     
    public void setUpLeafletPanel(){
        List<Leaflet> leaflets = selectedCreature.getLeaflets();
        for (int index = 0; index<3; index++){
            Leaflet leaflet = leaflets.get(index);
            int totalMagentaJewel = leaflet.getTotalNumberOfType(Constants.COLOR_MAGENTA) == -1 ? 0 : leaflet.getTotalNumberOfType(Constants.COLOR_MAGENTA);
            int totalBlueJewel =  leaflet.getTotalNumberOfType(Constants.COLOR_BLUE)== -1 ? 0 : leaflet.getTotalNumberOfType(Constants.COLOR_BLUE);
            int totalRedJewel =  leaflet.getTotalNumberOfType(Constants.COLOR_RED)== -1 ? 0 : leaflet.getTotalNumberOfType(Constants.COLOR_RED);
            int totalGreenJewel =  leaflet.getTotalNumberOfType(Constants.COLOR_GREEN)== -1 ? 0 : leaflet.getTotalNumberOfType(Constants.COLOR_GREEN);
            int totalWhiteJewel =  leaflet.getTotalNumberOfType(Constants.COLOR_WHITE)== -1 ? 0 : leaflet.getTotalNumberOfType(Constants.COLOR_WHITE);
            int totalYellowJewel = leaflet.getTotalNumberOfType(Constants.COLOR_YELLOW)== -1 ? 0 : leaflet.getTotalNumberOfType(Constants.COLOR_YELLOW);
            int totalPayment = leaflet.getPayment();
            int status = leaflet.getSituation();
            leafletTable.setValueAt(totalRedJewel, 0, index+1);
            leafletTable.setValueAt(totalGreenJewel, 1, index+1);
            leafletTable.setValueAt(totalBlueJewel, 2, index+1);
            leafletTable.setValueAt(totalMagentaJewel, 3, index+1);
            leafletTable.setValueAt(totalWhiteJewel, 4, index+1);
            leafletTable.setValueAt(totalYellowJewel, 5, index+1);
            leafletTable.setValueAt(totalPayment, 6, index+1);
            leafletTable.setValueAt(status, 7, index+1);
        }
        
    }
     
    public void setUpScorePanel(){
        scoreTextField.setText(Double.toString(selectedCreature.getAttributes().getScore()));
    }
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton antiClockwiseRotationButton;
    private javax.swing.JPanel bagPanel;
    private javax.swing.JTable bagTable;
    private javax.swing.JButton clockwiseRotationButton;
    private javax.swing.JButton createCreatureButton;
    private javax.swing.JComboBox<String> creatureColorComboBox;
    private javax.swing.JLabel creatureColorLabel;
    private javax.swing.JLabel creatureXPositionLabel;
    private javax.swing.JTextField creatureXPositionTextField;
    private javax.swing.JLabel creatureYPositionLabel;
    private javax.swing.JTextField creatureYPositionTextField;
    private javax.swing.JButton eatButton;
    private javax.swing.JPanel fuelPane;
    private javax.swing.JProgressBar fuelProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton leafletButton;
    private javax.swing.JPanel leafletPanel;
    private javax.swing.JTable leafletTable;
    private javax.swing.JPanel moveCreaturePanel;
    private javax.swing.JButton moveDownButton;
    private javax.swing.JButton moveUpButton;
    private javax.swing.JPanel newCreaturePanel;
    private javax.swing.JLabel pitchLabel;
    private javax.swing.JSlider pitchSlider;
    private javax.swing.JButton putInBagButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JTextField scoreTextField;
    private javax.swing.JComboBox<String> selectCreatureComboBox;
    private javax.swing.JPanel socrePanel;
    private javax.swing.JLabel thsLabel;
    private javax.swing.JLabel updateCreatureLabel;
    private javax.swing.JPanel updateCreaturePanel;
    private javax.swing.JLabel zeroLabel;
    // End of variables declaration//GEN-END:variables

   
}
