/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.Constants;
import ws3dproxy.CommandExecException;
import ws3dproxy.WS3DProxy;
import ws3dproxy.model.Creature;
import ws3dproxy.model.World;

/**
 *
 * @author lucas
 */
public class CreatureFrame extends javax.swing.JFrame {
    
    WS3DProxy proxy;
    World world;
    /**
     * Creates new form CreatureFrame
     */
    public CreatureFrame(WS3DProxy proxy, World world) {
        this.proxy = proxy;
        this.world = world;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCreaturePanel = new javax.swing.JPanel();
        creatureColorComboBox = new javax.swing.JComboBox<>();
        creatureColorLabel = new javax.swing.JLabel();
        creatureXPositionLabel = new javax.swing.JLabel();
        creatureYPositionLabel = new javax.swing.JLabel();
        creatureXPositionTextField = new javax.swing.JTextField();
        creatureYPositionTextField = new javax.swing.JTextField();
        createCreatureButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creature");
        setAlwaysOnTop(true);

        newCreaturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Creature", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        creatureColorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Green", "Blue", "Yellow", "Magenta", "White", "Dark Gray", "Orange" }));

        creatureColorLabel.setText("Color");

        creatureXPositionLabel.setText("X position ");

        creatureYPositionLabel.setText("Y position");

        creatureXPositionTextField.setText("0");

        creatureYPositionTextField.setText("0");

        createCreatureButton.setText("Create Creature");
        createCreatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCreatureButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newCreaturePanelLayout = new javax.swing.GroupLayout(newCreaturePanel);
        newCreaturePanel.setLayout(newCreaturePanelLayout);
        newCreaturePanelLayout.setHorizontalGroup(
            newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCreaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newCreaturePanelLayout.createSequentialGroup()
                        .addComponent(creatureColorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(creatureColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCreaturePanelLayout.createSequentialGroup()
                        .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creatureXPositionLabel)
                            .addComponent(creatureYPositionLabel))
                        .addGap(4, 4, 4)
                        .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creatureXPositionTextField)
                            .addComponent(creatureYPositionTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newCreaturePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createCreatureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        newCreaturePanelLayout.setVerticalGroup(
            newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCreaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creatureColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creatureColorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creatureXPositionLabel)
                    .addComponent(creatureXPositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newCreaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creatureYPositionLabel)
                    .addComponent(creatureYPositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createCreatureButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCreaturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCreaturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCreatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCreatureButtonActionPerformed
        try {
            int xPosition = Integer.parseInt(creatureXPositionTextField.getText());
            int yPosition = Integer.parseInt(creatureYPositionTextField.getText());
            int color = creatureColorComboBox.getSelectedIndex();
            JOptionPane.showMessageDialog(this, color);
            Creature c = this.proxy.createCreature(xPosition,yPosition,0,color);
            c.start();
        } catch (CommandExecException ex) {
            Logger.getLogger(CreatureFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createCreatureButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form s
        java.awt.EventQueue.invokeLater(new Runnable() {;;
            public void run() {
                new CreatureFrame().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createCreatureButton;
    private javax.swing.JComboBox<String> creatureColorComboBox;
    private javax.swing.JLabel creatureColorLabel;
    private javax.swing.JLabel creatureXPositionLabel;
    private javax.swing.JTextField creatureXPositionTextField;
    private javax.swing.JLabel creatureYPositionLabel;
    private javax.swing.JTextField creatureYPositionTextField;
    private javax.swing.JPanel newCreaturePanel;
    // End of variables declaration//GEN-END:variables
}
